package com.example.trekking_app.model;

public enum ErrorType {
    /* General Errors */
    ILLEGAL_ARGUMENTS,
    ALREADY_VERIFIED,
    NOT_VERIFIED,

    /* Signup Errors */
    EMPTY_FIELD,
    DUPLICATE_EMAIL_FOUND,
    EMAIL_NOT_FOUND,
    SIGNUP_FAILED,
    LOGIN_FAILED,
    DELETE_USER_FAILED,
    CREATE_ROUTE_FAILED,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE_FOUND,
    RESOURCE_UPDATE_FAILED,
    RESOURCE_DELETE_FAILED,
    RESOURCE_CREATE_FAILED,
    NO_RESOURCE_FOUND,
    ROUTE_NOT_FOUND,
    DESTINATION_NOT_FOUND,
    DUPLICATE_DESTINATION_FOUND,
    FILE_PARSING_FAILED
}
